# tish-learn build pipeline. 100% Tish toolchain.
#
# Build artifacts go into public/dist:
#   - learn.js              (tish build --target js app/main.tish)
#   - lattish-runtime.js    (tish build on lattish/src/Lattish.tish)
#   - tish-sw.js            (tish build on tish-browser-server/src/sw_worker.tish)
#   - tish_vm.{js,wasm}     (cargo + wasm-bindgen)
#   - tish_compiler.{js,wasm} (cargo + wasm-bindgen)
#
# learn.css is generated by `tish run build-css.tish` and lives at public/learn.css.

export CARGO_TARGET_DIR := justfile_directory() + "/target"
TISH_ROOT := env_var_or_default("TISH_ROOT", justfile_directory() + "/../tish")

default:
    @just --list

# Iframe runtime for the in-browser sandbox. Bundles Lattish + tish-ide-panels'
# iframe-shims (serve / fs / fetch / BroadcastChannel) into one flat JS file
# that gets prepended to compiled lesson code in the srcdoc iframe.
build-runtime:
    mkdir -p "{{ justfile_directory() }}/public/dist"
    tish build "{{ justfile_directory() }}/node_modules/tish-ide-panels/src/iframe-runtime.tish" \
        -o "{{ justfile_directory() }}/public/dist/lattish-runtime.js" \
        --target js

# Compile the tish-learn UI app -> public/dist/learn.js (depends on sandbox split + iframe runtime).
build-app: build-runtime build-sandbox
    mkdir -p "{{ justfile_directory() }}/public/dist"
    tish build "{{ justfile_directory() }}/app/main.tish" \
        -o "{{ justfile_directory() }}/public/dist/learn.js" \
        --target js

# Compile the Service Worker source -> public/dist/tish-sw.js
build-sw:
    mkdir -p "{{ justfile_directory() }}/public/dist"
    tish build "{{ justfile_directory() }}/node_modules/tish-browser-server/src/sw_worker.tish" \
        -o "{{ justfile_directory() }}/public/dist/tish-sw.js" \
        --target js

# CSS via the pure-Tish tish-tailwind emitter (no npm tailwindcss CLI).
build-css:
    tish run --feature fs --feature http "{{ justfile_directory() }}/build-css.tish"

# Build the bytecode VM WASM (uses tish_wasm_runtime crate).
build-vm:
    mkdir -p "{{ justfile_directory() }}/public/dist"
    cargo build -p tishlang_wasm_runtime --manifest-path "{{ TISH_ROOT }}/Cargo.toml" --target wasm32-unknown-unknown --release --features browser
    wasm-bindgen "{{ CARGO_TARGET_DIR }}/wasm32-unknown-unknown/release/tishlang_wasm_runtime.wasm" \
        --out-dir "{{ justfile_directory() }}/public/dist" --out-name tish_vm --target web

# Build the in-browser compiler WASM.
build-compiler:
    mkdir -p "{{ justfile_directory() }}/public/dist"
    cargo build -p tishlang_compiler_wasm --manifest-path "{{ TISH_ROOT }}/Cargo.toml" --target wasm32-unknown-unknown --release
    wasm-bindgen "{{ CARGO_TARGET_DIR }}/wasm32-unknown-unknown/release/tishlang_compiler_wasm.wasm" \
        --out-dir "{{ justfile_directory() }}/public/dist" --out-name tish_compiler --target web

# Static HTML per chapter (pure Tish: prerender.tish + same parser as the app).
build-prerender:
    tish run --feature fs "{{ justfile_directory() }}/prerender.tish"

# Standalone /sandbox bundle (code-split from main learn.js).
build-sandbox:
    mkdir -p "{{ justfile_directory() }}/public/dist"
    tish build "{{ justfile_directory() }}/app/main_sandbox.tish" \
        -o "{{ justfile_directory() }}/public/dist/learn_sandbox.js" \
        --target js

# Everything.
build: build-app build-sw build-css build-vm build-compiler build-prerender

# Build then serve. Default port 8765 (override with PORT=...).
dev: build
    tish run --feature fs --feature http --feature process "{{ justfile_directory() }}/dev-server.tish"

# Quick rebuild of just the Tish app + CSS (skip Rust toolchain).
quick: build-app build-sandbox build-css build-prerender

# Wipe build outputs.
clean:
    rm -rf "{{ justfile_directory() }}/public/dist" "{{ justfile_directory() }}/public/learn.css" "{{ justfile_directory() }}/public/content"
